Use new --context subctl flags
submariner-io/shipyard pull request #1005
Opened 2022-10-28 14:33 UTC by skitt

--kubecontext and --kubecontexts are deprecated.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

2022-10-28 15:56 UTC, tpantelis approved these changes

2022-10-30 08:41 UTC, mkolesnik requested changes
There's also usage of `--kubecontext` in `scripts/shared/lib/deploy_operator`

2022-10-31 08:56 UTC, skitt commented
> There's also usage of `--kubecontext` in `scripts/shared/lib/deploy_operator`

There is, thanks!

2022-11-02 12:29 UTC, mkolesnik approved these changes

2022-11-02 12:32 UTC, mkolesnik commented
> > There's also usage of `--kubecontext` in `scripts/shared/lib/deploy_operator`
> 
> There is, thanks!

Unfortunately it breaks the upgrade job :(
I guess we'll have to keep the `kubecontext` variant for join/deploy-broker to support these jobs until 0.14 is released..

2022-11-03 09:01 UTC, merged