Support Ginkgo v2 only
submariner-io/shipyard pull request #1103
Opened 2023-01-10 16:21 UTC by skitt

Now that all Submariner projects have switched to Ginkgo v2, we can drop support for v1.

Depends on https://github.com/submariner-io/subctl/pull/466
Signed-off-by: Stephen Kitt <skitt@redhat.com>

2023-01-16 13:25 UTC, mkolesnik requested changes
Few tweaks, otherwise LGTM

2023-01-16 13:25 UTC, mkolesnik commented on scripts/shared/e2e.sh
> +        -submariner-namespace $SUBM_NS "${clusters[@]/#/-dp-context=}" \
```suggestion
    "${GO:-go}" test -v -timeout 30m -args -test.timeout 15m \
        -submariner-namespace "$SUBM_NS" "${clusters[@]/#/-dp-context=}" \
```

These should be quoted though, as we dont want them accidentally splitting.

2023-01-16 13:25 UTC, mkolesnik commented on scripts/shared/unit_test.sh
> +        ${GO:-go} test -v ${race} -coverprofile unit.coverprofile "${packages[@]}" --ginkgo.v --ginkgo.trace --ginkgo.junit-report junit.xml "$@" && \
```suggestion
        "${GO:-go}" test -v ${race} -coverprofile unit.coverprofile "${packages[@]}" --ginkgo.v --ginkgo.trace --ginkgo.junit-report junit.xml "$@" && \
```

Same here

2023-01-16 15:30 UTC, skitt commented
We can’t do this, Coastguard still uses Ginkgo v1 and can’t migrate to v2 (it relies on old frameworks).

2023-01-16 16:59 UTC, tpantelis approved these changes

2023-01-16 18:03 UTC, sridhargaddam approved these changes

2023-01-16 18:20 UTC, tpantelis commented
> We can’t do this, Coastguard still uses Ginkgo v1 and can’t migrate to v2 (it relies on old frameworks).

https://github.com/submariner-io/coastguard/pull/115 switches **coastguard** to v2.

2023-01-18 14:55 UTC, mkolesnik approved these changes

2023-01-18 15:16 UTC, merged