Consolidate GHA testing workflows
submariner-io/shipyard pull request #1115
Opened 2023-01-23 11:38 UTC by mkolesnik

There are many testing workflows sprinkled around there, this consolidates them into one workflow for testing, making tracking all the different testing jobs easier.

See individual commits for more details and easier review.

2023-01-30 13:01 UTC, tpantelis requested changes

2023-01-30 13:01 UTC, tpantelis commented on .github/workflows/testing.yml
> +    name: Make clean-clusters
I prefer the names to reflect the purpose as phrases rather than the internal make target. 

```suggestion
    name: Clean up clusters
```

2023-01-30 13:01 UTC, tpantelis commented on .github/workflows/testing.yml
> +    name: Make clean-generated
```suggestion
    name: Clean up generated files
```

2023-01-30 13:01 UTC, tpantelis commented on .github/workflows/testing.yml
> +    name: Make e2e
```suggestion
    name: E2E
```

2023-01-30 13:01 UTC, tpantelis commented on .github/workflows/testing.yml
> +    name: Make deploy
```suggestion
    name: Deploy
```

2023-01-30 13:01 UTC, tpantelis commented on .github/workflows/testing.yml
> +    name: Make multiarch-images
```suggestion
    name: Make multi-arch images
```

2023-01-30 13:01 UTC, tpantelis commented on .github/workflows/testing.yml
> +    name: Make post-mortem
```suggestion
    name: Post mortem
```

2023-01-30 13:01 UTC, tpantelis commented on .github/workflows/testing.yml
> +    name: Make unit
```suggestion
    name: Unit tests
```

2023-02-21 16:51 UTC, tpantelis approved these changes

2023-03-01 08:14 UTC, skitt approved these changes

2023-03-21 13:27 UTC, merged