Bump to Fedora 39
submariner-io/shipyard pull request #1466
Opened 2023-11-08 11:33 UTC by skitt

This brings Go 1.21. Go 1.21 no longer ships .a libraries, so the corresponding clean-up is removed.

Python is upgraded to 3.12, which breaks j2cli; this switches to the packaged python3-jinja2-cli instead. The latter has progressed since j2cli was created, and should support all the j2cli features needed in Submariner (more precisely, for OVN).

The official GitHub client is available as a package, install that instead of the upstream tarball.

2023-11-08 11:37 UTC, sridhargaddam requested changes

2023-11-08 11:37 UTC, sridhargaddam commented on package/Dockerfile.shipyard-dapper-base
> -    pip install j2cli[yaml] --user && \
Please update Line25

2023-11-08 14:23 UTC, sridhargaddam approved these changes

2023-11-08 15:36 UTC, dfarrell07 approved these changes

2023-11-08 16:03 UTC, skitt commented
The switch to `jinja2` breaks OVN deployments; that can probably be worked around externally. The best solution would be to migrate OVNKubernetes to `jinja2` as well, but before we’d be able to use that we’d have to fix the deployment issues we run into when trying to use newer versions of OVNK...

2023-11-10 03:25 UTC, tpantelis approved these changes

2023-11-14 00:39 UTC, merged