Update K8s versions tested in E2E
submariner-io/shipyard pull request #1475
Opened 2023-11-20 16:48 UTC by dfarrell07

Add Kubernetes 1.26-1.28, remove end-of-life 1.22-1.25.

2023-11-21 09:30 UTC, skitt approved these changes

2023-11-21 13:31 UTC, sridhargaddam approved these changes

2023-11-21 14:17 UTC, dfarrell07 commented
[E2E Consuming (submariner, helm, libreswan, 1.28)](https://github.com/submariner-io/shipyard/actions/runs/6944542483/job/18891896039?pr=1475#logs) failed, re-running.

2023-11-21 19:35 UTC, tpantelis requested changes
Let's hold off on this a bit - see https://github.com/submariner-io/submariner-operator/pull/2895#discussion_r1400716484

2023-12-14 12:51 UTC, tpantelis approved these changes

2023-12-14 13:41 UTC, merged