Genericize base dapper logic
submariner-io/shipyard pull request #1497
Opened 2023-12-06 11:24 UTC by mkolesnik

Make base dapper logic project agnostic so that it can be consumed by projects outside the submariner org.
This mainly involves moving out basic dapper functions out to `Makefile.dapper.base` and adding an `ORG` argument to specify the organization.
References to `submariner-io` have been removed where possible.

2023-12-22 10:12 UTC, skitt requested changes

2023-12-22 10:12 UTC, skitt commented on scripts/shared/deploy.sh
> +[[ "$PROVIDER" == kind ]] || run_all_clusters schedule_dummy_pod
Isn’t this the wrong way round? If `schedule_dummy_pod` is supposed to run with kind,

```
[[ "$PROVIDER" != kind ]] || run_all_clusters schedule_dummy_pod
```

2024-01-22 13:34 UTC, skitt approved these changes

2024-01-23 17:08 UTC, tpantelis approved these changes

2024-01-23 17:23 UTC, merged