Default to K8s 1.28 in e2e
submariner-io/shipyard pull request #1538
Opened 2024-01-25 12:46 UTC by skitt

Other GHAs were changed to default to 1.28, but the custom GHA used throughout Submariner wasn't updated and still defaulted to 1.25. This fixes that.

2024-01-25 12:58 UTC, tpantelis requested changes

2024-01-25 12:58 UTC, tpantelis commented on gh-actions/e2e/action.yaml
> +    default: '1.28'
```suggestion
    default: '1.29'
```

2024-01-25 13:00 UTC, tpantelis commented
Shouldn't we default to 1.29?

2024-01-25 14:00 UTC, skitt commented
> Shouldn't we default to 1.29?

Not if we want to be able to run the e2e jobs — we can update this once we get a new version of kind.

2024-01-25 14:06 UTC, tpantelis approved these changes

2024-01-25 15:59 UTC, skitt commented
#1539 should fix the cleanup failures.

2024-01-29 15:22 UTC, aswinsuryan approved these changes

2024-01-29 15:31 UTC, merged