Bump helm from 3.12.3 to 3.14.1 for CVE-2024-25620
submariner-io/shipyard pull request #1563
Opened 2024-02-16 04:36 UTC by dfarrell07

Update generated by:

```
go get -u helm.sh/helm/v3@v3.14.1
go mod tidy
<manually undo go min-version/toolchain updates>
```

Issue identified by a Dependabot alert (#1560) on devel.

2024-02-16 09:33 UTC, skitt requested changes
Please redo this without `-u` to reduce the amount of churn. See https://github.com/submariner-io/shipyard/pull/1555#issuecomment-1948029416 for details.

2024-02-19 09:19 UTC, skitt approved these changes
My bad, `go get` produces the same result, mostly because Helm 3.14.1 itself pulls in updated dependencies (including `k8s.io` 0.29.0). This doesn’t actually matter because the `tools` module is separate from the main one.

2024-02-19 13:17 UTC, Jaanki commented
@dfarrell07 does this need to be backported to 0.15?

2024-02-19 13:17 UTC, Jaanki approved these changes

2024-02-19 13:17 UTC, merged

2024-02-19 15:41 UTC, dfarrell07 commented
> @dfarrell07 does this need to be backported to 0.15?

This dependency doesn't exist on 0.15