Add makefile support for ovn
submariner-io/shipyard pull request #398
Opened 2021-01-06 10:06 UTC by vthapar

* Adds `using=ovn` flag
* Adds `cluster_settings.ovn` file
* Handles dummy code to handle `ovn` cni in clusters.sh

Fixes: #335

Signed-off-by: Vishal Thapar <5137689+vthapar@users.noreply.github.com>

2021-01-06 11:02 UTC, mkolesnik requested changes
Looks good so far, a couple of small suggestions

2021-01-06 11:02 UTC, mkolesnik commented on scripts/shared/clusters.sh
> +        deploy_kind_ovn
```suggestion
        deploy_kind_ovn
        return
```

2021-01-06 11:02 UTC, mkolesnik commented on Makefile
> +endif
```suggestion
endif

```

2021-01-07 12:07 UTC, mkolesnik approved these changes
Looks good except one small nit but not blocking for merge

Don't forget to squash when merging, please :)

2021-01-07 12:07 UTC, mkolesnik commented on scripts/shared/clusters.sh
> +    fi
```suggestion
    fi

```

Sorry missed this nit the first time

2021-01-07 12:21 UTC, skitt approved these changes

2021-01-07 12:41 UTC, mangelajo approved these changes
Looks good to me, we will need an additional PR to label any of the worker nodes as gateway.

2021-01-07 13:36 UTC, merged

2022-03-28 19:38 UTC, dfarrell07 commented
This was backported in https://github.com/submariner-io/shipyard/pull/436.