Specify the repo/version when deploying the broker
submariner-io/shipyard pull request #464
Opened 2021-03-01 11:01 UTC by skitt

Now that the broker is operator-based, we need to specify the
repository and version we want to use.

This needs https://github.com/submariner-io/submariner-operator/pull/1118

Fixes: submariner-io/submariner-operator#1110
Signed-off-by: Stephen Kitt <skitt@redhat.com>

2021-03-01 12:04 UTC, mangelajo approved these changes

2021-03-01 13:55 UTC, SteveMattar requested changes
The variable names were changed in the last PR

2021-03-01 13:55 UTC, SteveMattar commented on scripts/shared/lib/deploy_operator
> +        subctlrepver="--repository ${SUBM_ENGINE_IMAGE_REPO} --version ${SUBM_ENGINE_IMAGE_TAG}"
```suggestion
	    if [ "${SUBM_GATEWAY_IMAGE_TAG}" != "subctl" ]; then
        subctlrepver="--repository ${SUBM_GATEWAY_IMAGE_REPO} --version ${SUBM_GATEWAY_IMAGE_TAG}"
```

2021-03-02 12:47 UTC, skitt commented on scripts/shared/lib/deploy_operator
> +        subctlrepver="--repository ${SUBM_ENGINE_IMAGE_REPO} --version ${SUBM_ENGINE_IMAGE_TAG}"
Thanks, done!

2021-03-02 13:48 UTC, SteveMattar approved these changes

2021-03-03 17:42 UTC, tpantelis approved these changes

2021-03-04 10:08 UTC, mangelajo approved these changes

2021-03-04 10:08 UTC, merged