Pass cluster/service CIDRs to subctl join
submariner-io/shipyard pull request #505
Opened 2021-03-29 16:15 UTC by dfarrell07

These CIDRs are always generated in utils/add_cluster_cidrs, along with
the existing global_cidr. They are also already passed by default in
deploy_helm/helm_install_subm.

Alternative implementation of idea in #504.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

2021-03-29 16:44 UTC, dfarrell07 commented
Here it is working, from the logs of the Shared Scripts/Deploy (operator) job:

> subctl join --kubeconfig /go/src/github.com/submariner-io/shipyard/output/kubeconfigs/kind-config-cluster1 --clusterid cluster1 --repository localhost:5000 --version local --nattport 4500 --ikeport 500 --colorcodes blue --clustercidr 10.1.0.0/16 --servicecidr 100.1.0.0/16 --globalnet-cidr  --disable-nat --cable-driver libreswan /go/src/github.com/submariner-io/shipyard/output/broker-info.subm

2021-03-30 11:22 UTC, skitt approved these changes
Given that the CIDR arrays are always supposed to be populated, this seems fine to me.

2021-03-31 07:01 UTC, mangelajo requested changes
Is there any reason why we need this always?

We will stop testing auto-detection of that which is done by the operator .

I think it's better to just do it in the necessary cases (like mkimura's patch for external network support).

2021-03-31 14:51 UTC, dfarrell07 commented
Ah good catch regarding not testing auto-detection @mangelajo, I didn't think about that.

Reopened @mkimuram's https://github.com/submariner-io/shipyard/pull/504 implementation.

2021-03-31 14:51 UTC, closed without merging