Add pre/post hooks to deploy/cleanup script and focus/skip to e2e script
submariner-io/shipyard pull request #509
Opened 2021-03-30 23:47 UTC by mkimuram

This PR adds below features to shipyard e2e scripts:

- Pre/post hooks in deploy/cleanup script
- Focus/skip in e2e script

Fixes: #508

2021-03-30 23:48 UTC, mkimuram commented
As described in commmit messages, these features can be used:

- Pre/post hooks in deploy/cleanup script:
```
export PLUGIN=/go/src/github.com/submariner-io/shipyard/scripts/shared/resources/plugins/sample_hook
make deploy
make cleanup
```

- Focus/skip in e2e script:
```
export FOCUS="\[example\]"
export SKIP="Should be able to list"
make e2e
```

2021-03-30 23:50 UTC, mkimuram commented
@dfarrell07 

I've implemented the scripts. Please review it.

2021-03-31 15:09 UTC, dfarrell07 reviewed
This is great @mkimuram, thank you! One very minor nit inline.

2021-03-31 15:09 UTC, dfarrell07 commented on gh-actions/e2e/action.yaml
> +    description: '-ginkgo.focus argument to passed to e2e tests'
```suggestion
    description: '-ginkgo.focus argument to passed to E2E tests'
```

Nit: I think we capitalize it consistently in this context, so let's continue doing so.

2021-03-31 15:09 UTC, dfarrell07 commented on gh-actions/e2e/action.yaml
> +    description: '-ginkgo.skip argument to passed to e2e tests'
```suggestion
    description: '-ginkgo.skip argument to passed to E2E tests'
```

2021-03-31 15:11 UTC, dfarrell07 commented
There are also some commit message linting issues:

```
gitlint --commits origin/devel..HEAD
Commit 9d8033a5fe:
10: B1 Line exceeds max length (100>80): "export PLUGIN=/go/src/github.com/submariner-io/shipyard/scripts/shared/resources/plugins/sample_hook"

Commit aad86c5d2d:
5: B1 Line exceeds max length (86>80): "- The value of `FOCUS` environment variable is added with --focus option to `E2E_ARGS`"
7: B1 Line exceeds max length (84>80): "- The value of `SKIP` environment variable is added with --skip option to `E2E_ARGS`"
```

2021-03-31 15:12 UTC, dfarrell07 commented
And also some shellcheck linting issues:

```
shellcheck -e SC2154 scripts/shared/lib/*

In scripts/shared/lib/utils line 138:
    type -t $func | grep -q function || return 0
            ^---^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    type -t "$func" | grep -q function || return 0


In scripts/shared/lib/utils line 139:
    eval $@
         ^-- SC2068: Double quote array expansions to avoid re-splitting elements.

For more information:
  https://www.shellcheck.net/wiki/SC2068 -- Double quote array expansions to ...
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
```

2021-03-31 17:48 UTC, mkimuram commented
@dfarrell07 

Thank you for your review. Fixed lint and commit issues and changed e2e to E2E.
It seems that the upgrade test is failing. I'm investigating it.

2021-03-31 20:59 UTC, dfarrell07 commented
> It seems that the upgrade test is failing. I'm investigating it.

@mkimuram It's not related to your PR, you can ignore it.

2021-03-31 21:00 UTC, dfarrell07 approved these changes
Thanks for the quality PR @mkimuram! LGTM :+1:

2021-04-06 02:53 UTC, tpantelis requested changes
Overall looks good.

2021-04-06 02:53 UTC, tpantelis commented on gh-actions/e2e/action.yaml
> +    description: '-ginkgo.focus argument to passed to E2E tests'
```suggestion
    description: '-ginkgo.focus argument to pass to E2E tests'
```

2021-04-06 02:53 UTC, tpantelis commented on gh-actions/e2e/action.yaml
> +    description: '-ginkgo.skip argument to passed to E2E tests'
```suggestion
    description: '-ginkgo.skip argument to pass to E2E tests'
```

2021-04-06 15:18 UTC, tpantelis approved these changes

2021-04-06 16:20 UTC, merged