Add staticcheck initialisations
submariner-io/shipyard pull request #523
Opened 2021-04-15 07:06 UTC by Jaanki

The defaults come from https://staticcheck.io/docs/#configuration

Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

2021-04-26 09:26 UTC, skitt requested changes

2021-04-26 09:26 UTC, skitt commented on staticcheck.conf
> +	"XML", "XMPP", "XSRF", "XSS"]
Please use `inherit`, see Lighthouse or Submariner:

```suggestion
initialisms = ["inherit", "CNI", "IPAM"]
```

2021-05-03 15:14 UTC, skitt approved these changes

2021-05-03 15:34 UTC, tpantelis approved these changes

2021-05-03 15:35 UTC, merged