Linting in a small image
submariner-io/shipyard pull request #564
Opened 2021-05-24 10:46 UTC by mkolesnik

Most linting commands (except golangci-lint) are self contained programs
with a relatively small footprint.
This change breaks them out to a separate Dockerfile which is based on
alpine and results in a tiny image (~80Mb on the filesystem) which
should make linting happen much faster (especially on the CI that has to
download the linting image).

If all consuming projects adopt this change, we can remove the linting
commands from the base image which should help reduce its size as well.

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2021-05-24 10:50 UTC, mangelajo approved these changes

2021-05-25 14:56 UTC, dfarrell07 requested changes, later dismissed

2021-05-25 14:56 UTC, dfarrell07 commented on package/Dockerfile.shipyard-linting
> +    pip install gitlint && \
I think we're supposed to remove npm and pip after these installs?

https://github.com/submariner-io/shipyard/blob/devel/package/Dockerfile.shipyard-dapper-base#L45

2021-05-25 14:58 UTC, dfarrell07 commented on package/Dockerfile.shipyard-linting
> +    pip install gitlint && \
Or I guess this is handled by `apk del installers`?

2021-05-25 15:08 UTC, dfarrell07 approved these changes

2021-05-25 16:49 UTC, skitt approved these changes

2021-05-26 02:26 UTC, tpantelis approved these changes

2021-05-26 02:26 UTC, merged