Fix gitlint
submariner-io/shipyard pull request #586
Opened 2021-06-17 11:50 UTC by mkolesnik

For some reason it explicitly needs `six` now

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2021-06-17 13:43 UTC, tpantelis commented
Can you provide more detail in the PR desc, eg what problem was observed?

2021-06-17 18:03 UTC, dfarrell07 commented
> Can you provide more detail in the PR desc, eg what problem was observed?

It was on Mikes other Shipyard PR (https://github.com/submariner-io/shipyard/pull/585):

```
[linting]$ make gitlint
gitlint --commits origin/devel..HEAD
Traceback (most recent call last):
  File "/usr/bin/gitlint", line 5, in <module>
    from gitlint.cli import cli
  File "/usr/lib/python3.9/site-packages/gitlint/cli.py", line 14, in <module>
    from gitlint.git import GitContext, GitContextError, git_version
  File "/usr/lib/python3.9/site-packages/gitlint/git.py", line 4, in <module>
    import arrow
  File "/usr/lib/python3.9/site-packages/arrow/__init__.py", line 2, in <module>
    from .api import get, now, utcnow
  File "/usr/lib/python3.9/site-packages/arrow/api.py", line 12, in <module>
    from arrow.arrow import TZ_EXPR, Arrow
  File "/usr/lib/python3.9/site-packages/arrow/arrow.py", line 31, in <module>
    from dateutil import tz as dateutil_tz
  File "/usr/lib/python3.9/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/usr/lib/python3.9/site-packages/dateutil/tz/tz.py", line 19, in <module>
    import six
ModuleNotFoundError: No module named 'six'
make: *** [Makefile.inc:119: gitlint] Error 1
```

2021-06-17 18:03 UTC, dfarrell07 approved these changes

2021-06-17 20:30 UTC, tpantelis approved these changes

2021-06-18 07:46 UTC, skitt requested changes
Here’s the explanation, it would be great if the commit message could be updated to include it!

The `six` module is installed as an APK because `pip` depends on it. `gitlint` also requires it (transitively), and `pip` finds the already-installed version. But then `apk del installers` removes `pip` and all its dependencies, including `six`, breaking `gitlint`.

Installing `py3-six` separately works around this by avoiding its removal in the `installers` group.

2021-06-20 10:06 UTC, sridhargaddam approved these changes

2021-06-20 11:50 UTC, tpantelis commented
> Here’s the explanation, it would be great if the commit message could be updated to include it!
> 

Done.

2021-06-20 12:22 UTC, merged