test(deploy): add OCM deploy tool
submariner-io/shipyard pull request #678
Opened 2021-11-16 15:33 UTC by SteveMattar

Test Submariner using OCM

* Rename the deploytool from olm to bundle
* Create common deploy functions
* Bump olm default version to v0.18.3
* Install `yq` in `shipyard-dapper-base image`
* Add ocm deploy tool
* The new deploy tool is now part of the CI

Closes #657

2021-11-17 16:46 UTC, skitt requested changes

2021-11-17 16:46 UTC, skitt commented on package/Dockerfile.shipyard-dapper-base
> +    GOFLAGS="" go get -v github.com/mikefarah/yq/v4 && \
Please adjust this to take `YQ_VERSION` into account, and delete line 75.

2021-11-18 08:17 UTC, skitt approved these changes

2021-11-24 18:47 UTC, dfarrell07 reviewed
Some suggestions inline. I know some comments are on only-moved code, but it seems to me this is still a good time to improve that code.

2021-11-24 18:47 UTC, dfarrell07 commented on scripts/shared/deploy.sh
> +  # shellcheck disable=SC2034
```suggestion
  # shellcheck disable=SC2034 # this variable is used elsewhere
```

2021-11-24 18:47 UTC, dfarrell07 commented on scripts/shared/deploy.sh
> +  # Wait for the catalogSource Readiness
```suggestion
  # Wait for the CatalogSource readiness
```

2021-11-24 18:47 UTC, dfarrell07 commented on scripts/shared/deploy.sh
> +  kubectl -n ${MARKETPLACE_NAMESPACE} get packagemanifests --ignore-not-found | grep "${cs}" || true
Do we want to keep these in?

2021-11-24 18:47 UTC, dfarrell07 commented on scripts/shared/deploy.sh
> +  echo "[INFO](${cluster}) Create the Operator group ${og}..."
```suggestion
  echo "[INFO](${cluster}) Create the OperatorGroup ${og}..."
```

2021-11-24 18:47 UTC, dfarrell07 commented on scripts/shared/deploy.sh
> +  kubectl get og -n "${ns}" --ignore-not-found
Do we want to keep this?

2021-11-24 18:47 UTC, dfarrell07 commented on scripts/shared/deploy.sh
> +  kubectl get pods -n "${ns}" --ignore-not-found
Do we want to keep this?

2021-11-24 18:47 UTC, dfarrell07 commented on scripts/shared/deploy.sh
> +  echo "[INFO](${cluster}) Approve the installPlan..."
```suggestion
  echo "[INFO](${cluster}) Approve the InstallPlan..."
```

2021-11-24 18:47 UTC, dfarrell07 commented on scripts/shared/deploy.sh
> +  # Delete previous catalogSource and Subscription
```suggestion
  # Delete previous CatalogSource and Subscription
```

2021-11-24 18:47 UTC, dfarrell07 commented on scripts/shared/lib/deploy_ocm
> +  # shellcheck disable=SC2153
Can we add explanations for all shellcheck ignores? (example elsewhere)

2021-11-24 18:47 UTC, dfarrell07 commented on scripts/shared/lib/deploy_ocm
> +
```suggestion
```

2021-11-24 18:47 UTC, dfarrell07 commented on scripts/shared/lib/deploy_ocm
> +      ### Wait for the managed cluster resource
```suggestion
      # Wait for the managed cluster resource
```

I wouldn't do these triple-comments, for consistency.

2021-11-24 18:47 UTC, dfarrell07 commented on scripts/shared/lib/deploy_ocm
> +      echo "[INFO](${cluster}) Accept the managed cluster ${mc} and approve its csr..."
```suggestion
      echo "[INFO](${cluster}) Accept the managed cluster ${mc} and approve its Certificate Signing Request (CSR)..."
```

2021-11-24 18:47 UTC, dfarrell07 commented on scripts/shared/lib/deploy_ocm
> +      ### Approve the managed cluster csr
```suggestion
      ### Approve the managed cluster CSR
```

2021-11-24 18:47 UTC, dfarrell07 commented on .github/workflows/scripts.yml
> +      - name: Setup kernel, increase the inotify settings
```suggestion
      - name: Set up kernel, increase the inotify settings
```

2021-11-24 18:47 UTC, dfarrell07 commented on scripts/shared/lib/deploy_ocm
> +  # Loop the submariner clusters and setup the managed cluster addon
```suggestion
  # Loop the submariner clusters and set up the managed cluster addon
```

2021-11-28 15:16 UTC, SteveMattar commented
Thanks for the comments @dfarrell07

2021-11-29 14:36 UTC, dfarrell07 approved these changes
Thanks @SteveMattar!

2021-11-29 19:41 UTC, merged