make clean-clusters is deleting images that it probably shouldn't
submariner-io/shipyard pull request #705
Opened 2022-01-14 21:08 UTC by Billy99

Running make deploy and make clean-clusters multiple times from a server on
corporate network and started hitting the Docker pull rate issue:
  "toomanyrequests: You have reached your pull rate limit"

Preload KIND image so docker pull failure can be added to a output signalling
a manual pull required. Also tag the imge so that it is not considered a
"dangling" image and deleted by "docker system prune" on "make clean-clusters".

Closes: #698

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>

2022-01-31 19:03 UTC, dfarrell07 approved these changes
LGTM, thanks @Billy99 and sorry for the slow review!

2022-01-31 19:41 UTC, Billy99 commented
/retest

2022-01-31 19:53 UTC, dfarrell07 commented
> /retest

We don't have Prow here, you have to click into the GHA and click "Rerun all jobs".

2022-02-02 07:19 UTC, sridhargaddam approved these changes
Thanks for the PR @Billy99

2022-02-02 12:24 UTC, mkolesnik requested changes
Let's have less nesting to make it easier to read and follow

2022-02-02 12:24 UTC, mkolesnik commented on scripts/shared/clusters.sh
> +    if [[ -n ${k8s_version} ]]; then
```suggestion
    if [[ -z "${k8s_version}" ]]; then
        echo "k8s_version not set."
        return
    fi
```

2022-02-02 12:24 UTC, mkolesnik commented on scripts/shared/clusters.sh
> +    # cleanup won't remove it.
```suggestion
# In development environments where clusters are brought up and down
# multiple times, several Docker images are repeatedly pulled and deleted,
# leading to the Docker error:
#   "toomanyrequests: You have reached your pull rate limit"
# Preload the KIND image. Also tag it so the `docker system prune` during
# cleanup won't remove it.
function download_kind() {
```

Wouldn't this make more sense?

2022-02-02 12:24 UTC, mkolesnik commented on scripts/shared/clusters.sh
> +        if [[ -z $(docker images -q "$kind_image_tag") ]] ; then
```suggestion
        if [[ -n $(docker images -q "$kind_image_tag") ]] ; then
            echo "Image $kind_image_tag already downloaded."
            return
        fi
```

2022-02-02 19:30 UTC, Billy99 reviewed
Since they were relatively minor changes, I collapsed the review comment changes instead of adding as separate commit.

2022-02-02 19:30 UTC, Billy99 commented on scripts/shared/clusters.sh
> +    # cleanup won't remove it.
Done

2022-02-02 19:30 UTC, Billy99 commented on scripts/shared/clusters.sh
> +    if [[ -n ${k8s_version} ]]; then
Done

2022-02-02 19:30 UTC, Billy99 commented on scripts/shared/clusters.sh
> +        if [[ -z $(docker images -q "$kind_image_tag") ]] ; then
Done

2022-02-03 08:39 UTC, skitt approved these changes

2022-02-21 14:01 UTC, nyechiel commented
@mkolesnik can you re-review please?

2022-02-22 16:45 UTC, nyechiel commented
@mkolesnik let's get this one in

2022-02-27 15:06 UTC, mkolesnik approved these changes

2022-02-27 15:29 UTC, merged