Consume ENV vars where possible
submariner-io/shipyard pull request #890
Opened 2022-07-27 14:04 UTC by mkolesnik

Instead of consuming flags, consume environment variables where
possible.
Some flags are retained for backwards compatibility not to break
consumers, and will be removed once their consumers are updated.

This is the first step in resolving #887 

Depends on #886 

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2022-07-28 11:03 UTC, skitt commented on .github/workflows/linting.yml
> +          size: 250
If this gets updated for any reason, could you mention this change in the corresponding commit message?

2022-07-28 11:18 UTC, skitt requested changes

2022-07-28 11:18 UTC, skitt commented on Makefile.inc
> +export CABLE_DRIVER = libreswan
Since these are exported further down, how about

    CABLE_DRIVER = lighthouse

Same for the other variables.

2022-07-28 14:23 UTC, skitt requested changes
Regarding the cache-removing commit, note that we only use `buildx` for multi-arch images.

2022-07-28 14:23 UTC, skitt commented on scripts/shared/lib/utils
> +   done
The safe way of doing this is

```
    for var; do
        declare -n value=$var
        printf '%s=%q\n' "$var" "$value"
    done
```

2022-08-01 05:38 UTC, mkolesnik commented on scripts/shared/lib/utils
> +   done
Cool, good to know :D

2022-08-01 05:42 UTC, mkolesnik commented
> Regarding the cache-removing commit, note that we only use `buildx` for multi-arch images.

Yes you're right of course, it's BuildKit that has the improvements (well probably buildx too as BuildKit is it's backed).
I updated the commit message.

2022-08-01 10:09 UTC, skitt approved these changes

2022-08-01 12:15 UTC, tpantelis approved these changes

2022-08-01 12:15 UTC, merged