Support multi arch compile inside `compile.sh`
submariner-io/shipyard pull request #895
Opened 2022-07-31 11:31 UTC by mkolesnik

Instead of relying on callers of the script to properly set the
`GOARCH`, detect it inside the script.

Callers can still set `GOARCH` if they choose to.

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2022-08-01 11:38 UTC, skitt requested changes

2022-08-01 11:38 UTC, skitt commented on scripts/shared/compile.sh
> +function determine_goarch() {
To clarify what this is supposed to do:

```suggestion
# Determine GOARCH based on the last component of the target directory, if any
function determine_goarch() {
```

2022-08-01 15:03 UTC, skitt approved these changes

2022-08-02 12:29 UTC, tpantelis approved these changes

2022-08-02 16:24 UTC, dfarrell07 approved these changes

2022-08-03 21:22 UTC, merged