Rename `DEBUG` to `DEBUG_PRINT`
submariner-io/shipyard pull request #911
Opened 2022-08-09 13:48 UTC by mkolesnik

Turns out the `DEBUG` env variable is used by `kubectl` (and probably
some of K8s go libraries) to control debug printing of network
connections.

Renaming our variable to `DEBUG_PRINT` to avoid this noise.

Example prints:
```
I0809 13:29:36.492157    5475 log.go:195] (0xc0006ee000) (0xc0008d6140) Create stream
I0809 13:29:36.492225    5475 log.go:195] (0xc0006ee000) (0xc0008d6140) Stream added, broadcasting: 1
I0809 13:29:36.493575    5475 log.go:195] (0xc0006ee000) Reply frame received for 1
I0809 13:29:36.493595    5475 log.go:195] (0xc0006ee000) (0xc0008d61e0) Create stream
I0809 13:29:36.493603    5475 log.go:195] (0xc0006ee000) (0xc0008d61e0) Stream added, broadcasting: 3
I0809 13:29:36.494109    5475 log.go:195] (0xc0006ee000) Reply frame received for 3
...
```

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2022-08-09 14:27 UTC, dfarrell07 approved these changes

2022-08-09 20:35 UTC, dfarrell07 commented
> ./scripts/shared/lib/debug_functions: line 17: trap: DEBUG_PRINT: invalid signal specification

2022-08-10 07:10 UTC, skitt requested changes

2022-08-10 07:10 UTC, skitt commented on scripts/shared/lib/debug_functions
> +          echo "${CYAN_COLOR}$cmd${NO_COLOR}" >&2; true' DEBUG_PRINT
```suggestion
          echo "${CYAN_COLOR}$cmd${NO_COLOR}" >&2; true' DEBUG
```

2022-08-11 08:42 UTC, mkolesnik commented on scripts/shared/lib/debug_functions
> +          echo "${CYAN_COLOR}$cmd${NO_COLOR}" >&2; true' DEBUG_PRINT
My `sed` was too aggressive :grimacing:

2022-08-11 08:54 UTC, mkolesnik commented
@dfarrell07 I added a small commit to the PR, to allow turning off debug printing only for specific functions, please re-review

2022-08-11 10:02 UTC, skitt approved these changes

2022-08-12 16:59 UTC, dfarrell07 approved these changes

2022-08-16 07:36 UTC, merged