Extract `exit_error` and `expect_env` functions
submariner-io/shipyard pull request #918
Opened 2022-08-17 07:31 UTC by mkolesnik

This logic repeats all over the place, extract small util functions to
cut down repetitiveness and do it properly.

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2022-08-17 08:19 UTC, skitt requested changes
A few drive-by spelling fixes, and use `printf` rather than `echo`.

2022-08-17 08:19 UTC, skitt commented on scripts/shared/compile.sh
> +[[ $# -eq 2 ]] || exit_error "The binary and source must be sepcified!"
Might as well fix the spelling ;-)

```suggestion
[[ $# -eq 2 ]] || exit_error "The binary and source must be specified!"
```

2022-08-17 08:19 UTC, skitt commented on scripts/shared/lib/deploy_funcs
> +    [[ -n "${namespace}" ]] || exit_error "Could not find a submariner deployment namespace"
```suggestion
    [[ -n "${namespace}" ]] || exit_error "Could not find a Submariner deployment namespace"
```

2022-08-17 08:19 UTC, skitt commented on scripts/shared/lib/utils
> +# Exit while printing an error message
```suggestion
# Exit after printing an error message
```

2022-08-17 08:19 UTC, skitt commented on scripts/shared/lib/utils
> +    >&2 echo -e "ERROR: $*"
```suggestion
    >&2 printf "ERROR: %s\n" "$*"
```

2022-08-17 08:19 UTC, skitt commented on test/scripts/compile/test.sh
> +        exit_error "Shoul'dve compiled ${arch@Q} but got $(file $binary)."
```suggestion
        exit_error "Should have compiled ${arch@Q} but got $(file $binary)."
```

2022-08-17 08:32 UTC, skitt approved these changes

2022-08-17 08:51 UTC, mkolesnik commented
Let's make sure to "squash & merge" as I used GH's apply suggestions

2022-08-18 16:14 UTC, dfarrell07 commented
> Let's make sure to "squash & merge" as I used GH's apply suggestions

Good test for this job, and yes it's properly gating.

> **Linting / No "Apply suggestions from code review" Commits (pull_request) ** Failing

2022-08-18 16:18 UTC, dfarrell07 approved these changes
Nice simplications, thanks Mike!

2022-08-18 17:17 UTC, dfarrell07 commented
Humm, because the squash commit is only created by the GitHub UI after tests, we can't use that method to get the `Linting / No "Apply suggestions from code review" Commits` job passing.

2022-08-19 07:15 UTC, skitt commented
> Humm, because the squash commit is only created by the GitHub UI after tests, we can't use that method to get the `Linting / No "Apply suggestions from code review" Commits` job passing.

Yes, the only way to handle this is for the submitter to squash locally and push. I changed the job to “Required” after Mike asked for a squash, because in my experience on Submariner such requests are pretty much guaranteed to result in an unsquashed rebase.

2022-08-22 07:37 UTC, merged