Support for air-gapped KIND environment
submariner-io/shipyard pull request #940
Opened 2022-09-12 07:50 UTC by mkolesnik

Preliminary support for "air-gapped" KIND environments, that works for iptables based CNIs and should work for OVN.

The "air-gap" is achieved by blocking outgoing traffic on the KIND node level, which blocks downloading images from any remote repository. Pods can still reach the outside network, however, as the pod networking goes through a different route.

To run, simply deploy with `USING=air-gap` or `AIR_GAPPED=true`.

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2022-09-19 09:34 UTC, skitt requested changes

2022-09-19 09:34 UTC, skitt commented on release-notes/20220911-air-gapped-kind.md
> +Support for simulated "air-gapped" environments has been added to KIND clusters.
```suggestion
Support for simulated "air-gapped" environments has been added to kind clusters.
```

2022-09-19 09:34 UTC, skitt commented on release-notes/20220911-air-gapped-kind.md
> +Support for simulated "air-gapped" environments has been added to KIND clusters.
Could you add more information on what this actually does?

2022-09-19 14:32 UTC, skitt approved these changes

2022-10-04 16:05 UTC, dfarrell07 approved these changes

2022-10-19 08:20 UTC, dfarrell07 commented
@mkolesnik Needs a manual rebase.

2022-10-20 14:44 UTC, merged