Stop vendoring
submariner-io/shipyard pull request #981
Opened 2022-10-17 11:14 UTC by skitt

go mod vendor is no longer necessary; see
https://go.dev/ref/mod#vendoring for details. Dependencies will be fulfilled using the module cache.

Fixes: #804
Signed-off-by: Stephen Kitt <skitt@redhat.com>

2022-12-27 13:19 UTC, mkolesnik requested changes

2022-12-27 13:19 UTC, mkolesnik commented on Makefile.inc
> +unit:
You should also remove it from `e2e` in `Makefile`

2023-01-02 13:10 UTC, mkolesnik approved these changes

2023-01-09 15:03 UTC, dfarrell07 approved these changes

2023-01-12 13:02 UTC, tpantelis approved these changes

2023-01-12 13:19 UTC, merged